### ISSUE TITLE
sample app doesnt work under msys

### ISSUE THREAD

**Issue by pm100** [crossterm-rs/crossterm#520] opened 2020-12-12 22:04 UTC
build this

https://github.com/crossterm-rs/crossterm/blob/master/examples/event-read.rs

on windows, (msvc tool chain). Runs fine normally but run it under MSYS2 and the input handling goes wonky

![image](https://user-images.githubusercontent.com/489231/101995907-9c433f80-3c82-11eb-8d45-7a4e57987c2a.png)

msys2 from here https://www.msys2.org/

I am happy to dig into this if you could give any suggestions as to where to poke at it

**Comment by Zapeth** [comment] 2021-06-24 20:30
Probably a duplicate of https://github.com/crossterm-rs/crossterm/issues/473

I suspect what happens is that the msys/mingw console is incorrectly recognized as a Windows console and therefore the [Windows system interface](https://github.com/crossterm-rs/crossterm/blob/master/src/terminal/sys/windows.rs) is used, when the [Unix system interface](https://github.com/crossterm-rs/crossterm/blob/master/src/terminal/sys/unix.rs) should be used instead.

This is just a theory though, proper support might be more involved than that.

**Comment by TimonPost** [comment] 2021-07-01 10:35
see: https://github.com/crossterm-rs/crossterm/issues/580

**Closed by TimonPost** 2021-07-01 10:35 UTC
