### ISSUE TITLE
Cursor reset_position() behaves weird when using linux compiled executable.

### ISSUE THREAD

**Issue by aleksmelnikov** [crossterm-rs/crossterm#194] opened 2019-08-22 09:43 UTC
Please, take a look at my simple example:
```
use crossterm::cursor;
fn main() {
let mut cursor = cursor();
/// Moving the cursor
// Set the cursor to position X: 10, Y: 5 in the terminal
cursor.goto(10,5);
// Move the cursor up,right,down,left 3 cells.
cursor.move_up(3);
cursor.move_right(3);
cursor.move_down(3);
cursor.move_left(3);
/// Safe the current cursor position to recall later
// Goto X: 5 Y: 5
cursor.goto(5,5);
// Safe cursor position: X: 5 Y: 5
cursor.save_position();
// Goto X: 5 Y: 20
cursor.goto(5,20);
// Print at X: 5 Y: 20.
print!("Yea!");
// Reset back to X: 5 Y: 5.
cursor.reset_position();
// Print 'Back' at X: 5 Y: 5.
print!("Back");
}

```
Which was compiled on Ubuntu 18.04.01 as `cargo build --target x86_64-pc-windows-gnu`
and then ran on Windows 10.
My output:
```
C:\opt>test_crossterm_1.exe


















     Yea!Back
C:\opt>
```

**Comment by TimonPost** [comment] 2019-08-27 19:12
Hi, thanks for leaving the comment, it seems to work when I compile and run it on windows. I will have a try to compile it on Linux for windows.

**Comment by TimonPost** [comment] 2019-09-23 17:02
I tried it there as well, can't directly see the issue here

**Comment by aleksmelnikov** [comment] 2019-09-24 19:08
Do you have got same pictures? Are they ok?

![crossterm](https://user-images.githubusercontent.com/22053918/65542331-a0692d00-df17-11e9-830b-4603cde0c4f6.JPG)

**Comment by TimonPost** [comment] 2019-09-25 05:24
Will run it again and show my result, there have been some problems with ssh clients in the past it might be caused by that

**Comment by aleksmelnikov** [comment] 2019-09-25 05:58
I compiled my project on a linux host then copied a binary file to a windows host and then ran that binary on it.
So, I don't use any ssh clients for the test on the left picture.

**Comment by TimonPost** [comment] 2020-07-02 12:26
I am going to close this issue, sorry for never comming back to it, the whole API is rewritten and thus this issue might have been resolved.

**Closed by TimonPost** 2020-07-02 12:26 UTC
