### ISSUE TITLE
Insert key doesnt reported to rust programs

### ISSUE THREAD

**Issue by og900aero** [crossterm-rs/crossterm#913] opened 2024-08-15 11:06 UTC
**Describe the bug**
I use yazi file manager [https://github.com/sxyazi/yazi](url)
I want to use Insert key for any function, but Yazi doesnt receives key events from crossterm.
The Yazi's developer thinks this is a crossterm's bug: [https://github.com/sxyazi/yazi/issues/1485](url)
The insert key is working fine. Xev program reported the following, when I press the insert key:

```
KeyPress event, serial 33, synthetic NO, window 0x1e00001,
    root 0x558, subw 0x0, time 1635077, (21,3), root:(988,565),
    state 0x0, keycode 90 (keysym 0xff9e, KP_Insert), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 33, synthetic NO, window 0x1e00001,
    root 0x558, subw 0x0, time 1635205, (21,3), root:(988,565),
    state 0x0, keycode 90 (keysym 0xff9e, KP_Insert), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**OS**
Debian 12
 
**Terminal/Console**
st 0.9.1

**Comment by joshka** [comment] 2024-08-20 10:39
The events reported in a window environment are different from those reported in a terminal emulator. Using xev creates a window to listen for key events as I understand it. The supported events are often even different in each terminal emulator. For background see https://sw.kovidgoyal.net/kitty/keyboard-protocol/ and http://www.leonerd.org.uk/hacks/fixterms/

You may be able to get this to work in some terminals (but not all) by turning on the keyboard enhancement flags - this would be something that yazi would have to do (and it still may not solve your problem).

You may be able to configure your terminal to do something special with Insert however and then configure yazi to recognize that.

I'm closing this as a duplicate of https://github.com/crossterm-rs/crossterm/issues/685 - you can add a comment there to help track this, but given this is in the keys not really supported by default you might be out of luck for really doing anything useful.

**Closed by joshka** 2024-08-20 10:39 UTC
