### ISSUE TITLE
Double key input on Windows

### ISSUE THREAD

**Issue by jasiukiewicztymon** [crossterm-rs/crossterm#772] opened 2023-04-01 22:03 UTC
**Describe the bug**
When I use the event::read function I have double input, and it does like I have clicked a key two times. When I tried it on my WSL it worked..

**To Reproduce**
1. Use the Rust tui lib tab example
2. Run the code on windows
3. See error

**Expected behavior**
Fix this

**OS**
 - Windows

**Terminal/Console**
 - CMD
 - PowerShell
 - Windows Terminal

**Comment by TimonPost** [comment] 2023-04-02 14:51
Its like key press/release

**Comment by jasiukiewicztymon** [comment] 2023-04-02 15:04
Ok.. but why it doesn't occur on every terminal but only on Window's one?

**Comment by TimonPost** [comment] 2023-04-02 15:18
good question, and actually, I think this needs to be reverted. On UNIX systems its supported under the kitty protocol. But as its not supported all over it should likely be disabled by default and enabled behind feature flag

**Comment by jasiukiewicztymon** [comment] 2023-04-02 15:23
ok, waiting to be fixed so... But it would be a big change no?

**Comment by TimonPost** [comment] 2023-04-02 15:33
not really. In the meantime just match on the https://docs.rs/crossterm/latest/crossterm/event/struct.KeyEvent.html `kind` field. So you can easily always make sure you are expecting key-press only..

**Comment by lesleyrs** [comment] 2023-04-02 15:38
I was just trying out `event-poll-read` as well using both wezterm and windows terminal on windows, wezterm doesn't actually have the double input problem. But it still has the enter release event at the start.

However I noticed that on WSL, there aren't any release events on either terminal. Am I not understanding something here?

**Comment by lesleyrs** [comment] 2023-04-06 01:48
Hey I spend some time figuring this out and I explained it in my PR.

But to sum it up:

cmd on conhost works as intended, then any other combination of cmd, powershell, conhost and wezterm (maybe others) works but you get the unintended "release" event at the start.

The only one which doesn't work well is windows terminal regardless of shell which means you can't use it for detecting held keys. They might get it fixed eventually as well, it's being tracked here https://github.com/crossterm-rs/crossterm/pull/775#issuecomment-1498296749. But it still works fine as long as you check for either press or release.

**Comment by lesleyrs** [comment] 2023-04-07 15:30
@TimonPost this one is already open for the same issue https://github.com/crossterm-rs/crossterm/issues/752

**Comment by TimonPost** [comment] 2023-04-07 16:19
Closing as duplicate then

**Closed** 2023-04-07 16:19 UTC
