### ISSUE TITLE
Performance regression issue in crossterm 0.23.0

### ISSUE THREAD

**Issue by ivanceras** [crossterm-rs/crossterm#635] opened 2022-02-24 21:00 UTC
**Describe the bug**

I experience a significant performance slowdown in my TUI framework.
The detailed issue is filed [here](https://github.com/ivanceras/titik/issues/3)

**To Reproduce**
1. Checkout titk TUI repo https://github.com/ivanceras/titik
2. Run the demo example with crossterm 0.18.0
  - `cargo run --release --example demo`
3. Interact with the TUI such as the tabs and textarea and notice how snappy it is.
4. Run the demo example with crossterm 0.23.0
  - `cargo run --release --example demo --no-default-features --features crossterm_new`
5. Notice the mouse clicks on the tabs takes longer to respond

**Expected behavior**

**OS**
 - Linux(ubuntu 20.04)

**Terminal/Console**
 - Gnome Terminal, the default terminal.

**Comment by sigmaSd** [comment] 2022-02-25 07:04
I tried both with gitpod.io/ and the speed feels exactly the same

**Comment by ivanceras** [comment] 2022-02-25 14:31
@sigmaSd what OS are you using and what terminal?

**Comment by sigmaSd** [comment] 2022-02-25 16:01
I tried with https://gitpod.io/ it uses ubuntu `5.13.0-1015-gcp #18-Ubuntu SMP Tue Feb 8 13:20:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by ivanceras** [comment] 2022-02-25 16:32
I just tried the gitpod.io as well, using the default terminal size there is not much difference in performance, but when you maximize the terminal panel, you will start to notice the difference in performance.

```sh
cargo run --release --example demo --no-default-features --features crossterm_new
```
It would also take several key presses on <kbd>CTRL-C</kdb> to terminate the demo.
After termination, you will see that using the the new version of crossterm, the demo is spilling out those ansi terminal codes in the window like this:

```sh
gitpod /workspace/titik (master) $ 35;42;24M35;44;25M35;47;28M35;49;31M35;52;33M35;55;35M35;58;36M35;63;38M35;65;40M35;64;40M35;63;39M35;62;39M35;62;38M35;61;38M35;60;38M35;60;37M35;59;37M35;59;36M35;59;35M35;59;34M35;60;33M35;60;32M35;60;31M0;60;31M0;60;31m35;60;31M35;60;30M35;60;29M0;60;29M0;60;29m0;60;29M0;60;29m35;59;29M35;58;28M35;56;28M35;53;28M35;49;27M35;47;27M35;46;26M35;45;26M35;45;25M35;46;25M35;47;25M35;47;24M35;48;24M35;49;24M35;50;24M35;51;25M35;52;25M35;53;25M35;54;25M35;55;26M35;56;26M35;57;27M35;58;27M35;59;28M35;60;28M0;60;28M0;60;28m35;60;28M35;59;28M51;59;28M^C
```
which it seems to me these are terminal inputs that were not able to be processed in the `event::read` function.

**Comment by ivanceras** [comment] 2022-02-25 16:42
I tested this is in Alacritty(in ubuntu) and Windows powershell and it works just fine without performance regression. This looks like Ubuntu specific only.

**Comment by sigmaSd** [comment] 2022-02-25 17:12
We probably can pinpoint the issue to the exact commit, since there isnt a lot of commits between 0.18 and 0.19 ( I'm assuming 0.19 have the performance regression?)

**Comment by ivanceras** [comment] 2022-02-25 17:31
So, I just point the crossterm_new feature to use 0.19.0 and it indeed is the start of the performance regression.

**Comment by markus-bauer** [comment] 2022-02-25 21:03
I think there might be a bug in your code. Or at least a difference between the two versions beyond just the version difference.
Try this: Go to the textbox and move the mouse back and forth.
With crossterm_new, the cursor follows the mouse, resulting in high cpu usage and slow ui. The old version doesn't do this.
When you don't move the mouse and just type, it's not that different to the old version.
Same for tabs: if you wiggle the mouse the ui becomes slow and if you wait it becomes normal again.
It looks like you changed how the mouse code works in between the two versions and that's what causes the difference.
Remember that crossterm sends mouse events all the time when moving the mouse.

**Comment by ivanceras** [comment] 2022-02-25 21:30
It could have been that the addition of `MouseEventKind::Moved` could contributed to this, since that event is triggered very rapidly. But, when I put a guarding condition to NOT process the statements block when the event that was read is a mouse moved, I still don't see an improvement in performance. It is still very slow. 
It seems like the mousemove is clogging the EventStream in crossterm.
Is there a way in crossterm to somehow, ignore the MouseMove event?

**Comment by sigmaSd** [comment] 2022-03-01 08:28
@ivanceras  There isn't currently, its enabled here https://github.com/crossterm-rs/crossterm/blob/9bc5cd3527a2d26caa6e2ccdc499beb4764fca95/src/event.rs#L249

If disabling this fixes you're issue I think its fair to make this more granular

**Comment by TimonPost** [comment] 2022-07-02 20:00
Closing in favour of #640

**Closed by TimonPost** 2022-07-02 20:00 UTC
